### ISSUE TITLE
Found a typo.

### ISSUE THREAD

**Issue by DeathNaughT-GitHub** [RandomDelta6/randomdelta6.github.io#1]
There's a typo in the ./blog/new/index.html file - typoed text: "Kalyani Government"
This text was right at the center of the page and therefore, easily caught.
![Screenshot_2020-04-06 RandomDelta6 randomdelta6 github io](https://user-images.githubusercontent.com/52620158/78529202-bf1d7a00-77fe-11ea-8d66-2afd491fb769.png)

**Comment by RandomDelta6** [comment]
Fixed.
